// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>
#include <RcppArmadillo.h>

using namespace Rcpp;

// matrix_cols
SEXP matrix_cols(SEXP mat_x, SEXP mat_y);
RcppExport SEXP _mclogit_fast_matrix_cols(SEXP mat_xSEXP, SEXP mat_ySEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<SEXP>::type mat_x(mat_xSEXP);
  Rcpp::traits::input_parameter<SEXP>::type mat_y(mat_ySEXP);
  rcpp_result_gen = Rcpp::wrap(matrix_cols(mat_x, mat_y));
  return rcpp_result_gen;
  END_RCPP
}
// fac_to_sparse
SEXP fac_to_sparse(Rcpp::IntegerVector vec, int levels);
RcppExport SEXP _mclogit_fast_fac_to_sparse(SEXP vecSEXP, SEXP levelsSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::IntegerVector>::type vec(vecSEXP);
  Rcpp::traits::input_parameter<int>::type levels(levelsSEXP);
  rcpp_result_gen = Rcpp::wrap(fac_to_sparse(vec, levels));
  return rcpp_result_gen;
  END_RCPP
}
// wsum_per_col_sparse
Rcpp::NumericVector wsum_per_col_sparse(SEXP x_exp, Rcpp::NumericVector y,
                                        Rcpp::NumericVector w);
RcppExport SEXP _mclogit_fast_wsum_per_col_sparse(SEXP x_expSEXP, SEXP ySEXP,
                                                  SEXP wSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<SEXP>::type x_exp(x_expSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type w(wSEXP);
  rcpp_result_gen = Rcpp::wrap(wsum_per_col_sparse(x_exp, y, w));
  return rcpp_result_gen;
  END_RCPP
}
// mclogit_fast_dense_fit
Rcpp::List mclogit_fast_dense_fit(Rcpp::NumericVector y, Rcpp::NumericVector s,
                                  Rcpp::NumericVector w, Rcpp::NumericMatrix x);
RcppExport SEXP _mclogit_fast_mclogit_fast_dense_fit(SEXP ySEXP, SEXP sSEXP,
                                                     SEXP wSEXP, SEXP xSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type s(sSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type w(wSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericMatrix>::type x(xSEXP);
  rcpp_result_gen = Rcpp::wrap(mclogit_fast_dense_fit(y, s, w, x));
  return rcpp_result_gen;
  END_RCPP
}
// mclogit_fast_dense_fit_pll
Rcpp::List mclogit_fast_dense_fit_pll(Rcpp::NumericVector y,
                                      Rcpp::NumericVector s,
                                      Rcpp::NumericVector w,
                                      Rcpp::NumericMatrix x);
RcppExport SEXP _mclogit_fast_mclogit_fast_dense_fit_pll(SEXP ySEXP, SEXP sSEXP,
                                                         SEXP wSEXP,
                                                         SEXP xSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type s(sSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type w(wSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericMatrix>::type x(xSEXP);
  rcpp_result_gen = Rcpp::wrap(mclogit_fast_dense_fit_pll(y, s, w, x));
  return rcpp_result_gen;
  END_RCPP
}
// mclogit_fast_sparse_fit_pll
Rcpp::List mclogit_fast_sparse_fit_pll(Rcpp::NumericVector y,
                                       Rcpp::NumericVector s,
                                       Rcpp::NumericVector w, SEXP x);
RcppExport SEXP _mclogit_fast_mclogit_fast_sparse_fit_pll(SEXP ySEXP,
                                                          SEXP sSEXP,
                                                          SEXP wSEXP,
                                                          SEXP xSEXP) {
  BEGIN_RCPP
  Rcpp::RObject rcpp_result_gen;
  Rcpp::RNGScope rcpp_rngScope_gen;
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type y(ySEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type s(sSEXP);
  Rcpp::traits::input_parameter<Rcpp::NumericVector>::type w(wSEXP);
  Rcpp::traits::input_parameter<SEXP>::type x(xSEXP);
  rcpp_result_gen = Rcpp::wrap(mclogit_fast_sparse_fit_pll(y, s, w, x));
  return rcpp_result_gen;
  END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mclogit_fast_matrix_cols", (DL_FUNC)&_mclogit_fast_matrix_cols, 2},
    {"_mclogit_fast_fac_to_sparse", (DL_FUNC)&_mclogit_fast_fac_to_sparse, 2},
    {"_mclogit_fast_wsum_per_col_sparse",
     (DL_FUNC)&_mclogit_fast_wsum_per_col_sparse, 3},
    {"_mclogit_fast_mclogit_fast_dense_fit",
     (DL_FUNC)&_mclogit_fast_mclogit_fast_dense_fit, 4},
    {"_mclogit_fast_mclogit_fast_dense_fit_pll",
     (DL_FUNC)&_mclogit_fast_mclogit_fast_dense_fit_pll, 4},
    {"_mclogit_fast_mclogit_fast_sparse_fit_pll",
     (DL_FUNC)&_mclogit_fast_mclogit_fast_sparse_fit_pll, 4},
    {NULL, NULL, 0}};

RcppExport void R_init_mclogit_fast(DllInfo* dll) {
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
}
