# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_cols <- function(mat_x, mat_y) {
    .Call(`_mclogit_fast_matrix_cols`, mat_x, mat_y)
}

fac_to_sparse <- function(vec, levels) {
    .Call(`_mclogit_fast_fac_to_sparse`, vec, levels)
}

wsum_per_col_sparse <- function(x_exp, y, w) {
    .Call(`_mclogit_fast_wsum_per_col_sparse`, x_exp, y, w)
}

mclogit_fast_dense_fit <- function(y, s, w, x) {
    .Call(`_mclogit_fast_mclogit_fast_dense_fit`, y, s, w, x)
}

mclogit_fast_dense_fit_pll <- function(y, s, w, x) {
    .Call(`_mclogit_fast_mclogit_fast_dense_fit_pll`, y, s, w, x)
}

mclogit_fast_sparse_fit_pll <- function(y, s, w, x) {
    .Call(`_mclogit_fast_mclogit_fast_sparse_fit_pll`, y, s, w, x)
}

